name: Build and push debug app

on:
  pull_request:

env:
  JAVA_OPTS: -Xmx12G

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 21
          cache: "gradle"

      - name: Write debug key
        shell: bash
        run: |
          echo "storeFile=~/.android/debug.keystore" > key.properties
          echo "storePassword=android" >> key.properties
          echo "keyPassword=android" >> key.properties
          echo "keyAlias=androiddebugkey" >> key.properties

      - name: Run tests
        run: ./gradlew test

      - name: Compile
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: numberhub-app-debug-apks
          path: app/build/outputs/apk/*/debug/app-*-debug.apk
